### ISSUE TITLE
Teslalogger not operational after upgrade to Version 1.56.0

### ISSUE THREAD

**Issue by ostorezio** [bassmaster187/TeslaLogger#1161]
** Append Logfile **

logger=sqlstore t=2024-01-24T14:59:02.113689609+01:00 level=info msg="Connecting to DB" dbtype=sqlite3
logger=migrator t=2024-01-24T14:59:02.215330795+01:00 level=info msg="Starting DB migrations"
logger=migrator t=2024-01-24T14:59:02.250642961+01:00 level=info msg="migrations completed" performed=0 skipped=485 duration=2.909241ms
logger=secrets t=2024-01-24T14:59:02.253130739+01:00 level=info msg="Envelope encryption state" enabled=true currentprovider=secretKey.v1
logger=sqlstore t=2024-01-24T14:59:02.253443794+01:00 level=info msg="Connecting to DB" dbtype=sqlite3
logger=migrator t=2024-01-24T14:59:02.36045498+01:00 level=info msg="Starting DB migrations"
logger=migrator t=2024-01-24T14:59:02.417655276+01:00 level=info msg="migrations completed" performed=0 skipped=485 duration=2.771722ms

24.01.2024 14:59:02 : Error: panic: duplicate metrics collector registration attempted

goroutine 1 [running]:
github.com/prometheus/client_golang/prometheus.(*Registry).MustRegister(0x7aba280, {0x80979a0, 0x1, 0x1})
	/opt/drone/gomodcache/github.com/prometheus/client_golang@v1.14.0/prometheus/registry.go:406 +0x88
github.com/prometheus/client_golang/prometheus.MustRegister(...)
	/opt/drone/gomodcache/github.com/prometheus/client_golang@v1.14.0/prometheus/registry.go:178
github.com/grafana/grafana/pkg/services/sqlstore.ProvideService(0x84e1800, 0x0, {0x3db0394, 0x5c591ec}, {0x3db84e8, 0x85bf390}, {0x3dbd908, 0x827f560})
	/drone/src/pkg/services/sqlstore/sqlstore.go:83 +0x228
github.com/grafana/grafana/pkg/cmd/grafana-cli/commands.runDbCommand.func1(0x7f79fe0)
	/drone/src/pkg/cmd/grafana-cli/commands/commands.go:52 +0x26c
github.com/urfave/cli/v2.(*Command).Run(0x5a91de8, 0x7f79fe0, {0x7ed6600, 0x1, 0x1})
	/opt/drone/gomodcache/github.com/urfave/cli/v2@v2.25.0/command.go:273 +0x8f0
github.com/urfave/cli/v2.(*Command).Run(0x5a91d38, 0x7f79ea0, {0x7ea1d70, 0x2, 0x2})
	/opt/drone/gomodcache/github.com/urfave/cli/v2@v2.25.0/command.go:266 +0xb30
github.com/urfave/cli/v2.(*Command).Run(0x5a92788, 0x7f79dc0, {0x7d3e4c8, 0x3, 0x3})
	/opt/drone/gomodcache/github.com/urfave/cli/v2@v2.25.0/command.go:266 +0xb30
github.com/urfave/cli/v2.(*Command).Run(0x80a8630, 0x7f79be0, {0x7fd6e80, 0x8, 0x8})
	/opt/drone/gomodcache/github.com/urfave/cli/v2@v2.25.0/command.go:266 +0xb30
github.com/urfave/cli/v2.(*Command).Run(0x80a8840, 0x7f79b00, {0x78420f0, 0x9, 0xa})
	/opt/drone/gomodcache/github.com/urfave/cli/v2@v2.25.0/command.go:266 +0xb30
github.com/urfave/cli/v2.(*App).RunContext(0x8424b00, {0x3dc0b50, 0x7846060}, {0x78420f0, 0x9, 0xa})
	/opt/drone/gomodcache/github.com/urfave/cli/v2@v2.25.0/app.go:332 +0x698
github.com/urfave/cli/v2.(*App).Run(...)
	/opt/drone/gomodcache/github.com/urfave/cli/v2@v2.25.0/app.go:309
main.main()
	/drone/src/pkg/cmd/grafana/main.go:39 +0x28c

24.01.2024 14:59:02 : Exec_mono: service grafana-server restart
24.01.2024 14:59:02 : Copy /etc/teslalogger/language-en.txt to /var/lib/grafana/plugins/teslalogger-timeline-panel/dist/language.txt
24.01.2024 14:59:02 : Copy /etc/teslalogger/settings.json to /var/lib/grafana/plugins/teslalogger-timeline-panel/dist/settings.json
24.01.2024 14:59:02 : End Grafana update
24.01.2024 14:59:04 : #1[:1]: LastTaskerToken not found - Stop using fast TaskerToken request! Reply: never!
24.01.2024 14:59:04 : Geofence initialized
24.01.2024 14:59:04 : Read Geofence File: /etc/teslalogger/geofence.csv
24.01.2024 14:59:05 : NearbySuCService initialized
24.01.2024 14:59:05 : Geofence: addresses inserted from geofence.csv: 7358
24.01.2024 14:59:05 : chmod 666 /etc/teslalogger/geofence-private.csv
24.01.2024 14:59:05 : Read Geofence File: /etc/teslalogger/geofence-private.csv
24.01.2024 14:59:05 : GeofencePrivate: Address inserted: Casa Villar
24.01.2024 14:59:05 : GeofencePrivate: Address inserted: Omron
24.01.2024 14:59:05 : GeofencePrivate: Address inserted: Casa Airassa
24.01.2024 14:59:05 : Geofence: addresses inserted from geofence-private.csv: 3
24.01.2024 14:59:07 : #1[Car_1:20]: GetAvgConsumption: sumkm: 4544.9; avgkm: 156.7; kwh/100km: 19.7; avgsocdiff: 43.8; maxkm: 364.9
24.01.2024 14:59:07 : #1[Car_1:20]: Restore Token OK. Age: 1/23/2024 11:42:25 AM
24.01.2024 14:59:07 : #1[Car_1:20]: TOKEN: XyJXbXXiOXXSXzIXNiXsXXR5XXIXIkXXVXIXXmtXXCX6IXpJXFXXQWXXQXV1XXZXRXXwUXXtXkhXWnXjXXJ9XXyXpcXMiXiXXdHXXcXovX2FXdXXudXXzXGEXY2XtXX9hXXRXMiX2MXIXXmFXXCX6IX93XmXXYXXXIXwiX3VXIXXiMXX2XWYXNjXtXXEzXX0XZGX4LXkXXTMXXGXzNXVhXTXXMjXXIXwiXXVXIXXbIXX0XHBXOiXvXXduXXIXYXXpLXRXX2xXXWX0bXJzXmXXbSXXLXJoXHRXcXXvLXX1XGgXdGXzXXEuXX9XL2XhdXRXXi9XXyX1cXVyXWXXbyXXLXJzX3AXOXXibXXlXmlXIiXiXX1hXXwXLCXvZXZXXW5XX2XjYXVzXyXXLCXXbXIiXltXLXXleXXiXjEXMDXwXXUzXXQXImXhdXIXXTcXXjXwNXU0XCXXb3XXYX9kXSIXIXXVIXXiXG9XYWXlXXoiXXQXSVXifX.XXiqXXiXbjXqeX7XXTsXXTX9BXKuX_XXXHXXnXfBXgtX9XXxYXXvX16XzaXEXXhmXXwXJpXVmXyXXRVXX3XnaXKhXnXX4MXXAX2FXO6XyXXziXXPXInX59XLXXa-XXVXQCXISXnXXKQXX8X2aX8qXyXX6PXXZXClXREXeXXljXXqXYVXZPXLXXQUXXYXiNXk6XiXXjyXXAX_RXa0XhXXolXXaXh7X-8XrXX5RXXuXqNXrLXZXXRlXXtX1_XuAXxXX5LXXEXflXIcXaXXqiXXXXq8XbzXrXXZJXXjXlrXFXXFXXkRXXuXKSXgJXiXXhwXXxXT1XbzXxXXgrXX0XOEXw
24.01.2024 14:59:26 : #1[Car_1:20]: HttpStatusCode = Unauthorized. Password changed or still valid? 0
24.01.2024 14:59:43 : UpdateDbInBackground started
24.01.2024 14:59:43 : UpdateAllPOIAddresses start
24.01.2024 15:00:00 : Reverse geocoding by Nominatim1
24.01.2024 15:00:05 : Reverse geocoding by Nominatim2
24.01.2024 15:00:11 : MySql.Data.MySqlClient.MySqlException (0x80004005): Duplicate entry '45.30345-7.918589' for key 'ix_key'
  at MySql.Data.MySqlClient.MySqlStream.ReadPacketAsync (System.Boolean execAsync) [0x00127] in <5af83e1b1b3246d78d7a16668621fd41>:0 
  at MySql.Data.MySqlClient.NativeDriver.GetResultAsync (System.Int32 affectedRow, System.Int64 insertedId, System.Boolean execAsync) [0x000fa] in <5af83e1b1b3246d78d7a16668621fd41>:0 
  at MySql.Data.MySqlClient.Driver.GetResultAsync (System.Int32 statementId, System.Int32 affectedRows, System.Int64 insertedId, System.Boolean execAsync) [0x00083] in <5af83e1b1b3246d78d7a16668621fd41>:0 
  at MySql.Data.MySqlClient.Driver.NextResultAsync (System.Int32 statementId, System.Boolean force, System.Boolean execAsync) [0x000b9] in <5af83e1b1b3246d78d7a16668621fd41>:0 
  at MySql.Data.MySqlClient.MySqlDataReader.NextResultAsync (System.Boolean execAsync, System.Threading.CancellationToken cancellationToken) [0x0020f] in <5af83e1b1b3246d78d7a16668621fd41>:0 
  at MySql.Data.MySqlClient.MySqlDataReader.NextResultAsync (System.Boolean execAsync, System.Threading.CancellationToken cancellationToken) [0x0077a] in <5af83e1b1b3246d78d7a16668621fd41>:0 
  at MySql.Data.MySqlClient.MySqlCommand.ExecuteReaderAsync (System.Data.CommandBehavior behavior, System.Boolean execAsync, System.Threading.CancellationToken cancellationToken) [0x004c1] in <5af83e1b1b3246d78d7a16668621fd41>:0 
  at MySql.Data.MySqlClient.MySqlCommand.ExecuteReaderAsync (System.Data.CommandBehavior behavior, System.Boolean execAsync, System.Threading.CancellationToken cancellationToken) [0x009da] in <5af83e1b1b3246d78d7a16668621fd41>:0 
  at MySql.Data.MySqlClient.MySqlCommand.ExecuteReaderAsync (System.Data.CommandBehavior behavior, System.Boolean execAsync, System.Threading.CancellationToken cancellationToken) [0x00aeb] in <5af83e1b1b3246d78d7a16668621fd41>:0 
  at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQueryAsync (System.Boolean execAsync, System.Threading.CancellationToken cancellationToken) [0x000c2] in <5af83e1b1b3246d78d7a16668621fd41>:0 
  at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery () [0x00012] in <5af83e1b1b3246d78d7a16668621fd41>:0 
  at TeslaLogger.SQLTracer.TraceNQ (MySql.Data.MySqlClient.MySqlCommand cmd, System.Int64& lastInsertedId, System.String callerFilePath, System.Int32 callerLineNumber) [0x00053] in <ea243b9fd7a344949770e4885a618cd8>:0 
  at TeslaLogger.GeocodeCache.Insert (System.Double lat, System.Double lng, System.String address) [0x0007d] in <ea243b9fd7a344949770e4885a618cd8>:0 
24.01.2024 15:00:11 : Reverse geocoding by Nominatim3
24.01.2024 15:00:13 : TeslaLogger process statistics
WorkingSet64:            80433152
PeakWorkingSet64:        90746880
PrivateMemorySize64:     88334336
VirtualMemorySize64:    135643136
StartTime: 1/24/2024 2:58:47 PM
Database sizes: DB teslalogger
  table pos has 208mb
  table can has 207mb
  table mothership has 15mb
  table superchargerstate has 9mb
  table charging has 6mb
  table drivestate has 2mb
  table TPMS has 1mb

24.01.2024 15:00:26 : #1[Car_1:20]: Update Tesla Token From Refresh Token!
24.01.2024 15:00:29 : UpdateAllPOIAddresses end 46170ms count:11
24.01.2024 15:00:32 : #1[Car_1:20]: HttpStatus: Forbidden
24.01.2024 15:00:32 : #1[Car_1:20]: Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
  at Newtonsoft.Json.JsonTextReader.ParseValue () [0x002b3] in <dd21e08747d94bcebed8b56112226337>:0 
  at Newtonsoft.Json.JsonTextReader.Read () [0x0004c] in <dd21e08747d94bcebed8b56112226337>:0 
  at Newtonsoft.Json.JsonReader.ReadAndMoveToContent () [0x00000] in <dd21e08747d94bcebed8b56112226337>:0 
  at Newtonsoft.Json.JsonReader.ReadForType (Newtonsoft.Json.Serialization.JsonContract contract, System.Boolean hasConverter) [0x0004a] in <dd21e08747d94bcebed8b56112226337>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType, System.Boolean checkAdditionalContent) [0x000db] in <dd21e08747d94bcebed8b56112226337>:0 
  at Newtonsoft.Json.JsonSerializer.DeserializeInternal (Newtonsoft.Json.JsonReader reader, System.Type objectType) [0x00054] in <dd21e08747d94bcebed8b56112226337>:0 
  at Newtonsoft.Json.JsonSerializer.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType) [0x00000] in <dd21e08747d94bcebed8b56112226337>:0 
  at Newtonsoft.Json.JsonConvert.DeserializeObject (System.String value, System.Type type, Newtonsoft.Json.JsonSerializerSettings settings) [0x0002d] in <dd21e08747d94bcebed8b56112226337>:0 
  at Newtonsoft.Json.JsonConvert.DeserializeObject (System.String value) [0x00000] in <dd21e08747d94bcebed8b56112226337>:0 
  at TeslaLogger.WebHelper.UpdateTeslaTokenFromRefreshToken () [0x0020e] in <ea243b9fd7a344949770e4885a618cd8>:0 
24.01.2024 15:00:32 : #1[Car_1:20]: GetVehicles: {"error":"token expired (401)"}
24.01.2024 15:00:32 : #1[Car_1:20]: ExitCarThread: wh.GetVehicles() == NULL
24.01.2024 15:00:32 : #1[Car_1:20]: *** Exit Loop !!!
24.01.2024 15:01:06 : Deleted Duplicate Trips: 0 Time: 36294ms
24.01.2024 15:01:06 : #1[DBUpdaterThread:18]: CombineChangingStates start
24.01.2024 15:01:06 : #1[DBUpdaterThread:18]: CombineChangingStates took 410ms
24.01.2024 15:01:06 : #1[DBUpdaterThread:18]: UpdateChargeEnergyAdded(1228): 1 rows updated to charge_energy_added 0
24.01.2024 15:01:06 : #1[DBUpdaterThread:18]: UpdateChargeEnergyAdded(1228): 1 rows updated to charge_energy_added 0
24.01.2024 15:01:07 : #1[DBUpdaterThread:18]: UpdateChargeEnergyAdded(1949): 1 rows updated to charge_energy_added 5.88
24.01.2024 15:01:07 : #1[DBUpdaterThread:18]: UpdateChargeEnergyAdded(1953): 1 rows updated to charge_energy_added 5.28
24.01.2024 15:01:07 : #1[DBUpdaterThread:18]: UpdateChargeEnergyAdded(1959): 1 rows updated to charge_energy_added 2.62
24.01.2024 15:01:07 : #1[DBUpdaterThread:18]: UpdateChargeEnergyAdded(1967): 1 rows updated to charge_energy_added 13.61
24.01.2024 15:01:07 : #1[DBUpdaterThread:18]: UpdateChargeEnergyAdded(1984): 1 rows updated to charge_energy_added 13.25
24.01.2024 15:01:07 : #1[DBUpdaterThread:18]: UpdateChargeEnergyAdded(1987): 1 rows updated to charge_energy_added 15.41
24.01.2024 15:01:07 : #1[DBUpdaterThread:18]: UpdateChargeEnergyAdded(1990): 1 rows updated to charge_energy_added 10.91
24.01.2024 15:01:07 : #1[DBUpdaterThread:18]: UpdateChargeEnergyAdded(2008): 1 rows updated to charge_energy_added 37.65
24.01.2024 15:01:07 : #1[DBUpdaterThread:18]: UpdateChargeEnergyAdded(2015): 1 rows updated to charge_energy_added 21.07
24.01.2024 15:01:07 : #1[DBUpdaterThread:18]: UpdateChargeEnergyAdded(2026): 1 rows updated to charge_energy_added 8.42
24.01.2024 15:01:07 : #1[DBUpdaterThread:18]: UpdateChargeEnergyAdded(1939): 1 rows updated to charge_energy_added 22.16
24.01.2024 15:01:07 : #1[DBUpdaterThread:18]: UpdateChargeEnergyAdded(1940): 1 rows updated to charge_energy_added 5.88
24.01.2024 15:01:07 : #1[DBUpdaterThread:18]: UpdateChargeEnergyAdded(1941): 1 rows updated to charge_energy_added 11.52
24.01.2024 15:01:08 : #1[DBUpdaterThread:18]: UpdateChargeEnergyAdded(1954): 1 rows updated to charge_energy_added 32.98
24.01.2024 15:01:08 : #1[DBUpdaterThread:18]: UpdateChargeEnergyAdded(1960): 1 rows updated to charge_energy_added 2.12
24.01.2024 15:01:08 : #1[DBUpdaterThread:18]: UpdateChargeEnergyAdded(1985): 1 rows updated to charge_energy_added 12.69
24.01.2024 15:01:08 : #1[DBUpdaterThread:18]: UpdateChargeEnergyAdded(1988): 1 rows updated to charge_energy_added 11.14
24.01.2024 15:01:08 : #1[DBUpdaterThread:18]: UpdateChargeEnergyAdded(2009): 1 rows updated to charge_energy_added 0.52
24.01.2024 15:01:08 : #1[DBUpdaterThread:18]: UpdateChargeEnergyAdded(2010): 1 rows updated to charge_energy_added 19.81
24.01.2024 15:01:08 : #1[DBUpdaterThread:18]: UpdateChargeEnergyAdded(2011): 1 rows updated to charge_energy_added 6.93
24.01.2024 15:01:08 : #1[DBUpdaterThread:18]: UpdateChargeEnergyAdded(2016): 1 rows updated to charge_energy_added 14.14
24.01.2024 15:01:08 : #1[DBUpdaterThread:18]: UpdateChargeEnergyAdded(2017): 1 rows updated to charge_energy_added 12.44
24.01.2024 15:01:08 : #1[DBUpdaterThread:18]: UpdateChargeEnergyAdded(2018): 1 rows updated to charge_energy_added 7.16
24.01.2024 15:01:08 : #1[DBUpdaterThread:18]: ShareData: Your charging data / degradation data will be shared anonymously to the community. Thank you!
24.01.2024 15:01:08 : #1[DBUpdaterThread:18]: ShareData: SendAllChargingData start
24.01.2024 15:01:08 : #1[DBUpdaterThread:18]: ShareData: SELECT chargingstate ms: 20
24.01.2024 15:01:08 : #1[DBUpdaterThread:18]: ShareData: SendAllChargingData finished
24.01.2024 15:01:08 : #1[DBUpdaterThread:18]: ShareData: SendDegradationData start
24.01.2024 15:01:08 : #1[DBUpdaterThread:18]: ShareData: SELECT degradation Data ms: 70
24.01.2024 15:01:14 : #1[DBUpdaterThread:18]: ShareData: OK
24.01.2024 15:01:14 : #1[DBUpdaterThread:18]: ShareData: SendDegradationData end
24.01.2024 15:01:14 : #1[DBUpdaterThread:18]: ShareData: SendAllDrivingData start
24.01.2024 15:01:14 : #1[DBUpdaterThread:18]: ShareData: SELECT drivestate ms: 180
24.01.2024 15:01:26 : Active_Cars_1
24.01.2024 15:01:26 : SearchFornewCars
24.01.2024 15:01:27 : UpdateDbInBackground finished, took 103967.538ms
24.01.2024 15:01:27 : RunHousekeepingInBackground started
24.01.2024 15:01:27 : Exec_mono: /bin/df -k
24.01.2024 15:01:27 :  Filesystem     1K-blocks     Used Available Use% Mounted on
/dev/root       29384700  7253340  20906296  26% /
devtmpfs         1867776        0   1867776   0% /dev
tmpfs            1999872       12   1999860   1% /dev/shm
tmpfs            1999872     9884   1989988   1% /run
tmpfs               5120        4      5116   1% /run/lock
tmpfs            1999872        0   1999872   0% /sys/fs/cgroup
/dev/loop0         92800    92800         0 100% /snap/core/16207
/dev/loop2         92800    92800         0 100% /snap/core/16098
/dev/loop1         42752    42752         0 100% /snap/certbot/3568
/dev/loop3         55168    55168         0 100% /snap/core20/2106
/dev/loop4         54656    54656         0 100% /snap/core20/2018
/dev/loop5         42624    42624         0 100% /snap/certbot/3463
/dev/mmcblk0p1    258095    52884    205211  21% /boot
/dev/sda1      754899880   939572 715543924   1% /var/lib/mysql
/dev/sda2      685149616 25341736 624934640   4% /etc/teslalogger
tmpfs             399972        0    399972   0% /run/user/0

24.01.2024 15:01:27 : Exec_mono: /usr/bin/du -sk /etc/teslalogger/backup
24.01.2024 15:01:27 :  22766208	/etc/teslalogger/backup

24.01.2024 15:01:27 : Exec_mono: /usr/bin/du -sk /etc/teslalogger/Exception
24.01.2024 15:01:28 :  428	/etc/teslalogger/Exception

24.01.2024 15:01:28 : Exec_mono: /usr/bin/du -sk /etc/teslalogger/nohup.out
24.01.2024 15:01:28 :  2204	/etc/teslalogger/nohup.out

24.01.2024 15:01:28 : Housekeeping: database usage (teslalogger)
24.01.2024 15:01:28 : Table:                  can data:  136 MB index:   72 MB rows:   3329434
24.01.2024 15:01:28 : Table:                  kvs data:    0 MB index:    0 MB rows:        19
24.01.2024 15:01:28 : Table:            httpcodes data:    0 MB index:    0 MB rows:        61
24.01.2024 15:01:28 : Table:   mothershipcommands data:    0 MB index:    0 MB rows:        75
24.01.2024 15:01:28 : Table:             journeys data:    0 MB index:    0 MB rows:         6
24.01.2024 15:01:28 : Table:                  pos data:  163 MB index:   45 MB rows:   1168148
24.01.2024 15:01:28 : Table:              candata data:    0 MB index:    0 MB rows:         0
24.01.2024 15:01:28 : Table:             charging data:    5 MB index:    2 MB rows:     39120
24.01.2024 15:01:28 : Table:                state data:    0 MB index:    0 MB rows:      5516
24.01.2024 15:01:28 : Table:           mothership data:   12 MB index:    4 MB rows:    213815
24.01.2024 15:01:28 : Table:    superchargerstate data:    9 MB index:    0 MB rows:    233295
24.01.2024 15:01:28 : Table:           drivestate data:    2 MB index:    0 MB rows:      4828
24.01.2024 15:01:28 : Table:        superchargers data:    0 MB index:    0 MB rows:       793
24.01.2024 15:01:28 : Table: active_route_energy_at_arrival data:    0 MB index:    0 MB rows:      3838
24.01.2024 15:01:28 : Table:        chargingstate data:    0 MB index:    0 MB rows:       563
24.01.2024 15:01:28 : Table:                 cars data:    0 MB index:    0 MB rows:         0
24.01.2024 15:01:28 : Table:                 TPMS data:    0 MB index:    0 MB rows:      5997
24.01.2024 15:01:28 : Table:           shiftstate data:    0 MB index:    0 MB rows:         0
24.01.2024 15:01:28 : Table:         geocodecache data:    0 MB index:    0 MB rows:       546
24.01.2024 15:01:28 : Table:          car_version data:    0 MB index:    0 MB rows:        41
24.01.2024 15:01:28 : Table:        teslacharging data:    0 MB index:    0 MB rows:        74
24.01.2024 15:01:28 : Housekeeping: database.mothership older than 14 days count: 10194 minID:19065001 maxID:19075194
24.01.2024 15:01:28 : Housekeeping: delete database.mothership chunk 19066001
24.01.2024 15:01:29 : Housekeeping: delete database.mothership chunk 19067001
24.01.2024 15:01:30 : Housekeeping: delete database.mothership chunk 19068001
24.01.2024 15:01:31 : Housekeeping: delete database.mothership chunk 19069001
24.01.2024 15:01:34 : Housekeeping: delete database.mothership chunk 19070001
24.01.2024 15:01:35 : Housekeeping: delete database.mothership chunk 19071001
24.01.2024 15:01:36 : Housekeeping: delete database.mothership chunk 19072001
24.01.2024 15:01:37 : Housekeeping: delete database.mothership chunk 19073001
24.01.2024 15:01:38 : Housekeeping: delete database.mothership chunk 19074001
24.01.2024 15:01:39 : Housekeeping: delete database.mothership chunk 19075001
24.01.2024 15:01:40 : Housekeeping: OPTIMIZE TABLE mothership
24.01.2024 15:01:58 : UpdateCO2

**Describe the bug**
  Access to Teslalogger webpage show most data missing or wrong

**To Reproduce**
  Loging to https://raspberry/admin/index.php

**Expected behavior**

**Screenshots**

<img width="1303" alt="Screen Shot 2024-01-24 at 3 02 45 PM" src="https://github.com/bassmaster187/TeslaLogger/assets/87861096/a7ad12ad-aa5c-469d-aeba-97d488ed8bc8">

** Teslalogger Type **
Linux raspberry 4.19.118-v7l+ #1311 SMP Mon Apr 27 14:26:42 BST 2020 armv7l GNU/Linux

** Do you use Tasker or iBeacon **

**Additional context**

**Comment by ostorezio** [comment]
OK; now it is working again, but I still get this exception in the log file:

26.01.2024 08:41:01 : MySql.Data.MySqlClient.MySqlException (0x80004005): Duplicate entry '45.125341-7.223693' for key 'ix_key'
  at MySql.Data.MySqlClient.MySqlStream.ReadPacketAsync (System.Boolean execAsync) [0x00127] in <5af83e1b1b3246d78d7a16668621fd41>:0 
  at MySql.Data.MySqlClient.NativeDriver.GetResultAsync (System.Int32 affectedRow, System.Int64 insertedId, System.Boolean execAsync) [0x000fa] in <5af83e1b1b3246d78d7a16668621fd41>:0 
  at MySql.Data.MySqlClient.Driver.GetResultAsync (System.Int32 statementId, System.Int32 affectedRows, System.Int64 insertedId, System.Boolean execAsync) [0x00083] in <5af83e1b1b3246d78d7a16668621fd41>:0 
  at MySql.Data.MySqlClient.Driver.NextResultAsync (System.Int32 statementId, System.Boolean force, System.Boolean execAsync) [0x000b9] in <5af83e1b1b3246d78d7a16668621fd41>:0 
  at MySql.Data.MySqlClient.MySqlDataReader.NextResultAsync (System.Boolean execAsync, System.Threading.CancellationToken cancellationToken) [0x0020f] in <5af83e1b1b3246d78d7a16668621fd41>:0 
  at MySql.Data.MySqlClient.MySqlDataReader.NextResultAsync (System.Boolean execAsync, System.Threading.CancellationToken cancellationToken) [0x0077a] in <5af83e1b1b3246d78d7a16668621fd41>:0 
  at MySql.Data.MySqlClient.MySqlCommand.ExecuteReaderAsync (System.Data.CommandBehavior behavior, System.Boolean execAsync, System.Threading.CancellationToken cancellationToken) [0x004c1] in <5af83e1b1b3246d78d7a16668621fd41>:0 
  at MySql.Data.MySqlClient.MySqlCommand.ExecuteReaderAsync (System.Data.CommandBehavior behavior, System.Boolean execAsync, System.Threading.CancellationToken cancellationToken) [0x009da] in <5af83e1b1b3246d78d7a16668621fd41>:0 
  at MySql.Data.MySqlClient.MySqlCommand.ExecuteReaderAsync (System.Data.CommandBehavior behavior, System.Boolean execAsync, System.Threading.CancellationToken cancellationToken) [0x00aeb] in <5af83e1b1b3246d78d7a16668621fd41>:0 
  at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQueryAsync (System.Boolean execAsync, System.Threading.CancellationToken cancellationToken) [0x000c2] in <5af83e1b1b3246d78d7a16668621fd41>:0 
  at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery () [0x00012] in <5af83e1b1b3246d78d7a16668621fd41>:0 
  at TeslaLogger.SQLTracer.TraceNQ (MySql.Data.MySqlClient.MySqlCommand cmd, System.Int64& lastInsertedId, System.String callerFilePath, System.Int32 callerLineNumber) [0x00053] in <ea243b9fd7a344949770e4885a618cd8>:0 
  at TeslaLogger.GeocodeCache.Insert (System.Double lat, System.Double lng, System.String address) [0x0007d] in <ea243b9fd7a344949770e4885a618cd8>:0 
26.01.2024 08:41:01 : Reverse geocoding by Nominatim6


  I think I can remove manually the duplicate entry from the DB, which table should I look for?

**Comment by superfloh247** [comment]
geocodecache

it's just a cache, you can wipe the table

**Comment by bassmaster187** [comment]
That exception shouldn't is not really bad

**Comment by ostorezio** [comment]
Yes, it looks like it is recurring, thanks
