### ISSUE TITLE
I am unable to add a vehicle with the latest version upgrade

### ISSUE THREAD

**Issue by jaimebennett** [bassmaster187/TeslaLogger#1314]
password_fleet.php:1 Uncaught SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Object.success (password_fleet.php?id=-1&AT=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6InE0dHg3Q1UyYzI2V1BiemwxZjZjanM3QnhzayJ9.eyJpc3MiOiJodHRwczovL2F1dGgudGVzbGEuY29tL29hdXRoMi92My9udHMiLCJhenAiOiI5MWQ0ZGEyYTM0NjgtNGI4MS1hZGJhLWQyYjI3MWJlZGZhMiIsInN1YiI6IjY4ZjgxODQ5LTAyMWQtNDJmOC1hYWNmLTk0OTJiN2U5NWNhNSIsImF1ZCI6WyJodHRwczovL2ZsZWV0LWFwaS5wcmQubmEudm4uY2xvdWQudGVzbGEuY29tIiwiaHR0cHM6Ly9mbGVldC1hcGkucHJkLmV1LnZuLmNsb3VkLnRlc2xhLmNvbSIsImh0dHBzOi8vYXV0aC50ZXNsYS5jb20vb2F1dGgyL3YzL3VzZXJpbmZvIl0sInNjcCI6WyJvcGVuaWQiLCJ2ZWhpY2xlX2RldmljZV9kYXRhIiwib2ZmbGluZV9hY2Nlc3MiLCJ1c2VyX2RhdGEiLCJ2ZWhpY2xlX2NtZHMiLCJ2ZWhpY2xlX2NoYXJnaW5nX2NtZHMiXSwiYW1yIjpbInB3ZCIsIm1mYSIsIm90cCJdLCJleHAiOjE3MTg3ODI4MzEsImlhdCI6MTcxODc1NDAzMSwib3VfY29kZSI6Ik5BIiwibG9jYWxlIjoiZW4tVVMiLCJhdXRoX3RpbWUiOjE3MTg3NTQwMzB9.rZ-UIXbMrcPVzA95OIpwTnYSSnWmdYwWrr6Xe7Z0jcnpYTlruBj18N0mUmwp1vEBeXUPorJnaBvZmpy7nucmiFiLkgdvclsAfMTAkQw4WNkgQ89ZuK7JnuUe86sf1RBVjQdbZwu7NjhtpPe7aiWPwWPyp2NqUYUr_YVmF4Xr7fjOTaFeLpTwwMoIkC73YBYdcnXeJopzjTpz9GpN4Ulvu8vOHMR04TM2HEmwJagvb-Xb_m8fC2gk5W82lGawyyaJzmGWlcsCN-QJKGn-AUQDF2HNj1WhALDja2S3KNi5VfGxyQ8aDWdTAWtRgFxul-KO3pRDSIdB75th3FIcH2B-gQ&RT=NA_44405fd451cdf0a548266f9aebf2b16cc2ab1449fd1f424b150a66784bf2bf53:163:21)
    at fire (jquery-1.12.4.js:3232:31)
    at Object.fireWith [as resolveWith] (jquery-1.12.4.js:3362:7)
    at done (jquery-1.12.4.js:9840:14)
    at XMLHttpRequest.callback (jquery-1.12.4.js:10311:8)

**Comment by bassmaster187** [comment]
Please try it with the new version
