### ISSUE TITLE
TelsaMate import tool failure

### ISSUE THREAD

**Issue by IMgoRt** [bassmaster187/TeslaLogger#410]
Attempting to use the new teslamate data import tool.
I run both on a server within docker instances.
Commands executed in powershell (x64) on windows 10

I've adjusted the teslamate yml
I've adjusted the exec.config to match my server based deployments
I've taken backups and stored safely

When I run .\bin\Teslamate-Import.exe it exits in a very short time and the logfile shows:
<System.IO.FileNotFoundException: Could not load file or assembly 'MySql.Data, Version=8.0.13.0, Culture=neutral, PublicKeyToken=c5687fc88969c44d' or one of its dependencies. The system cannot find the file specified.>

Thanks

**Comment by bassmaster187** [comment]
forgot to include dlls. Please get latest version and retry

**Comment by IMgoRt** [comment]
> forgot to include dlls. Please get latest version and retry

Thanks, next error:
- MySql.Data.MySqlClient.MySqlException (0x80004005): Unknown column 'import' in 'where clause'
   at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.GetResult(Int32 statementId, Int32& affectedRows, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
   at Teslamate_Import.Program.GetFirstTeslaloggerData()
   at Teslamate_Import.Program.Main(String[] args)
17/11/2020 16:01:24          - ***** Teslamate Import 1.1.0.0 Finish *****

**Comment by bassmaster187** [comment]
Please retry. Sorry!

**Comment by IMgoRt** [comment]
Is this a firewall configuration issue (everything runs on my private LAN
- Npgsql.NpgsqlException (0x80004005): Exception while connecting ---> System.Net.Sockets.SocketException (0x80004005): No connection could be made because the target machine actively refused it
   at Npgsql.NpgsqlConnector.Connect(NpgsqlTimeout timeout)
   at Npgsql.NpgsqlConnector.Connect(NpgsqlTimeout timeout)
   at Npgsql.NpgsqlConnector.<RawOpen>d__152.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.NpgsqlConnector.<Open>d__148.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.ConnectorPool.<AllocateLong>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Npgsql.NpgsqlConnection.<>c__DisplayClass32_0.<<Open>g__OpenLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.NpgsqlConnection.Open()
   at Teslamate_Import.Program.CopyPositions()
   at Teslamate_Import.Program.Main(String[] args)

**Comment by bassmaster187** [comment]
It seems like PostgreSQL doesn't expose it's port to outside of docker.

  database:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=teslamate
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=teslamate
    **ports:
        - 5432:5432**
    volumes:
      - teslamate-db:/var/lib/postgresql/data

**Comment by IMgoRt** [comment]
> It seems like PostgreSQL doesn't expose it's port to outside of docker.
> 
> database:
> image: postgres:13
> restart: always
> environment:
> - POSTGRES_USER=teslamate
> - POSTGRES_PASSWORD=secret
> - POSTGRES_DB=teslamate
> **ports: - 5432:5432**
> volumes:
> - teslamate-db:/var/lib/postgresql/data

That highlighted line was in the instructions and therefore in my .yml

**Comment by bassmaster187** [comment]
Please double check if teslamate's database ports are really open:
![image](https://user-images.githubusercontent.com/6816385/99666879-de0a0d00-2a6b-11eb-8bcb-ad1e75c61179.png)

Please try to connect to the teslamate database by any third party tools like https://dbeaver.io/ to make sure it is actually possible to connect to the database.

**Comment by IMgoRt** [comment]
> Please double check if teslamate's database ports are really open:
> ![image](https://user-images.githubusercontent.com/6816385/99666879-de0a0d00-2a6b-11eb-8bcb-ad1e75c61179.png)
> 
> Please try to connect to the teslamate database by any third party tools like https://dbeaver.io/ to make sure it is actually possible to connect to the database.

That's the issue - connection refused - how to proceed?

**Comment by bassmaster187** [comment]
So even dbeaver is not able to connect to teslamate's database? Please post the output of 
`docker ps`

**Comment by IMgoRt** [comment]
> So even dbeaver is not able to connect to teslamate's database? Please post the output of
> `docker ps`

![image](https://user-images.githubusercontent.com/53863760/99671017-57543080-2a69-11eb-8b8b-c5fa492c2b1f.png)

**Comment by bassmaster187** [comment]
Please restart Teslamate Database container, wait 5 minutes and post the database container logfile.

Maybe Port 5432 is already used on your host, so you could also try a different port.

**Comment by IMgoRt** [comment]
> Please restart Teslamate Database container, wait 5 minutes and post the database container logfile.
> 
> Maybe Port 5432 is already used on your host, so you could also try a different port.

Nothing in the log, logging appears to be turned off

**Comment by IMgoRt** [comment]
> Please restart Teslamate Database container, wait 5 minutes and post the database container logfile.
> 
> Maybe Port 5432 is already used on your host, so you could also try a different port.

`

2020-11-25 10:18:35.432 UTC [1] LOG:  database system is shut down | stderr
-- | --


`

**Comment by IMgoRt** [comment]
> Please restart Teslamate Database container, wait 5 minutes and post the database container logfile.
> 
> Maybe Port 5432 is already used on your host, so you could also try a different port.

`2020-11-25 10:18:35.432 UTC [1] LOG:  database system is shut down

PostgreSQL Database directory appears to contain a database; Skipping initialization
2020-11-25 10:19:07.676 UTC [1] LOG:  starting PostgreSQL 13.0 (Debian 13.0-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
2020-11-25 10:19:07.697 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2020-11-25 10:19:07.697 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2020-11-25 10:19:07.836 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2020-11-25 10:19:08.020 UTC [24] LOG:  database system was shut down at 2020-11-25 10:18:35 UTC
2020-11-25 10:19:08.471 UTC [1] LOG:  database system is ready to accept connections`

**Comment by IMgoRt** [comment]
How do I direct your code to a new port? :nnnn on the server IP returns "no such host is known"

Thanks

**Comment by bassmaster187** [comment]
I think, I don't understand exactly. "No such host is known" is pretty much a problem with DNS - so not the port is the problem. The Name is the problem.

**Comment by IMgoRt** [comment]
> I think, I don't understand exactly. "No such host is known" is pretty much a problem with DNS - so not the port is the problem. The Name is the problem.

I'll try again.
I've changed the port from 5432 to 9432 DBeaver can now connect to teslamate's DB on that port and examine the structure, etc.
What do I change within teslalogger to connect to the new port?

**Comment by IMgoRt** [comment]
> > I think, I don't understand exactly. "No such host is known" is pretty much a problem with DNS - so not the port is the problem. The Name is the problem.
> 
> I'll try again.
> I've changed the port from 5432 to 9432 DBeaver can now connect to teslamate's DB on that port and examine the structure, etc.
> What do I change within teslalogger to connect to the new port?

Investigation show port 5432 on Synology is used by Postgres - used by several internal features.
Hopefully you can adjust your code to allow a different port to be specified.

**Comment by bassmaster187** [comment]
Did you try to change the connection string to teslamate?

File: Teslamate-Import.exe.config
```
<setting name="TeslamateDB" serializeAs="String">
        <value>Host=localhost;Username=teslamate;Password=secret;Database=teslamate</value>
</setting>
```

**Comment by IMgoRt** [comment]
> Did you try to change the connection string to teslamate?
> 
> File: Teslamate-Import.exe.config
> 
> ```
> <setting name="TeslamateDB" serializeAs="String">
>         <value>Host=localhost;Username=teslamate;Password=secret;Database=teslamate</value>
> </setting>
> ```

I don't recall, I spun up a google cloud instance, restored my TM and then pulled that into TL as I was unable to work out another way around the issue

**Comment by bassmaster187** [comment]
Ok, so I'm closing this issue.
